

datatable:
    path: /
    defaults: { _controller: AppBundle:Default:grid }
    options:
        expose: true
    
datatable_list:
    path: /list
    defaults: { _controller: AppBundle:Default:index }
    options:
        expose: true


multiple_delete_route:
    path: /delete
    defaults: { _controller: AppBundle:Default:delete }
    options:
        expose: true
