

datatable:
    path: /
    defaults: { _controller: AppBundle:Default:grid }
    options:
        expose: true
    
datatable_list:
    path: /list
    defaults: { _controller: AppBundle:Default:index }
    options:
        expose: true


multiple_delete_route:
    path: /delete
    defaults: { _controller: AppBundle:Default:delete }
    options:
        expose: true

route_edit:
    path: /edit/{id}
    defaults: { _controller: AppBundle:Default:edit }
    options:
        expose: true


route_detail:
    path: /detail/{id}
    defaults: { _controller: AppBundle:Default:detail }
    options:
        expose: true
